#ifndef crypto_core_H
#define crypto_core_H

#include "crypto_core_aes256encrypt.h"

#define crypto_core crypto_core_aes256encrypt
#define crypto_core_OUTPUTBYTES crypto_core_aes256encrypt_OUTPUTBYTES
#define crypto_core_INPUTBYTES crypto_core_aes256encrypt_INPUTBYTES
#define crypto_core_KEYBYTES crypto_core_aes256encrypt_KEYBYTES
#define crypto_core_CONSTBYTES crypto_core_aes256encrypt_CONSTBYTES
#define crypto_core_PRIMITIVE "aes256encrypt"
#define crypto_core_IMPLEMENTATION crypto_core_aes256encrypt_IMPLEMENTATION
#define crypto_core_VERSION crypto_core_aes256encrypt_VERSION

#endif
